name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: |
        docker login -u ${{secrets.DOCKER USER}} -p ${{secrets.DOCKER PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/trading:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/trading